/* Compiles the template corpus into the prototype.

   Emits one JSON blob plus the shared evaluator source, and splices both into
   draft-ai-engine.html between the BUILD:CORPUS markers. The prototype stays a
   single self-contained file that runs from file:// — a fetch() of these JSON
   files would be blocked by CORS — but the corpus on disk remains the single
   source of truth, and `npm run check` proves the file is in sync. */
import fs from 'node:fs';
import path from 'node:path';
import {loadCorpus, ROOT} from './corpus.mjs';
import {allConfigs} from './evaluator.mjs';

const HTML = path.join(ROOT,'..','draft-ai-engine.html');
const START = '/* BUILD:CORPUS-START';
const END   = '/* BUILD:CORPUS-END */';

const C = loadCorpus();
const strip = f => fs.readFileSync(path.join(ROOT,'tools',f),'utf8')
  .replace(/^export /gm,'')
  .replace(/^\/\*[\s\S]*?\*\/\n/,'');            /* drop the file's own header comment */
const evaluator = strip('evaluator.mjs');
/* review.mjs imports the source standard; both are inlined so the engine's gate is the same
   code the validator runs, not a re-implementation that can drift from it. */
const sources   = strip('sources.mjs');
const review    = strip('review.mjs').replace(/^import .*\n/gm,'');

const meta = {
  builtFrom: 'templates/',
  clauses: C.clauses.length,
  documents: C.documents.length,
  rules: C.rules.length,
  fields: C.fields.length,
  glossaryTerms: Object.keys(C.glossary).length,
  questions: C.questions.length,
  risks: C.risks.length,
  benchmarks: C.benchmarks.length,
  configurations: allConfigs(C.taxonomy).length,
  files: C.files
};

const blob = {taxonomy:C.taxonomy, rules:C.rules, glossary:C.glossary,
              documents:C.documents, fields:C.fields, aliases:C.aliases,
              questions:C.questions, risks:C.risks, benchmarks:C.benchmarks, benchmarkSchema:{populatedBy:C.benchmarkSchema.populatedBy}, templateMeta:C.templateMeta, clauses:C.clauses, meta};

const block =
`${START} — generated by templates/tools/build.mjs from templates/. Do not edit by hand. */
const CORPUS = ${JSON.stringify(blob)};

/* ---- shared evaluation core, inlined verbatim from templates/tools/evaluator.mjs ---- */
${evaluator.trim()}

/* ---- source standard, inlined verbatim from templates/tools/sources.mjs ---- */
${sources.trim()}

/* ---- release gate, inlined verbatim from templates/tools/review.mjs ---- */
${review.trim()}
${END}`;

const html = fs.readFileSync(HTML,'utf8');
const i = html.indexOf(START), j = html.indexOf(END);
if(i<0||j<0){ console.error(`build: markers not found in ${HTML}`); process.exit(1); }
const next = html.slice(0,i) + block + html.slice(j+END.length);

const check = process.argv.includes('--check');
if(check){
  if(next!==html){ console.error('build --check: draft-ai-engine.html is stale — run `node templates/tools/build.mjs`'); process.exit(1); }
  console.log('build --check: prototype is in sync with templates/');
} else {
  fs.writeFileSync(HTML,next);
  console.log(`built ${meta.clauses} clauses · ${meta.documents} documents · ${meta.rules} rules · ${meta.fields} fields into ${path.basename(HTML)} (${(block.length/1024).toFixed(0)} KB)`);
}
