/* The drafting review packet.

   191 of the 360 clauses assert no law. They cannot be verified against a statute — there
   is nothing to verify against — and until now the release gate withheld them anyway, on a
   ladder built for citations. They are gated on draftingReviewLevels instead, which needs
   one thing this repo cannot produce: a named lawyer who has read them.

   This turns that into a packet somebody can actually work through. Grouped by document,
   because reviewing a whole MSA in one sitting is the only way the answers stay coherent;
   ordered inside each document by how much it costs to get wrong; and every clause carries
   the text, the fields it interpolates, when it appears, how much of the configuration
   space it reaches, and the exact JSON to paste back once it has been read.

   Reach is measured, not guessed: each clause is evaluated across the full enumerated
   configuration space, the same 12,120 answer sets the validator walks. A clause that
   appears in 2% of documents and a clause that appears in every one of them are not the
   same review job, and sorting by severity alone hides that.

   Usage: node templates/tools/drafting-packet.mjs [--doc <id>]
*/
import fs from 'node:fs';
import path from 'node:path';
import {loadCorpus, ROOT} from './corpus.mjs';
import {fireRules, clauseEligible, docIncluded, allConfigs} from './evaluator.mjs';
import {gateFor, lawTalk} from './review.mjs';
import {writeIfChanged, VOLATILE_FIELDS, VOLATILE_LINES} from './artifact.mjs';

const C = loadCorpus();
const TAX = C.taxonomy;
const only = process.argv.includes('--doc') ? process.argv[process.argv.indexOf('--doc')+1] : null;

const drafting = C.clauses.filter(c => c.assertsLaw === false && (!only || c.doc === only));
const docById  = new Map(C.documents.map(d=>[d.id,d]));

/* ---- reach: how much of the configuration space actually sees this clause ---- */
const configs = allConfigs(TAX);
const reach = new Map(drafting.map(c=>[c.id,0]));
let denominator = 0;
for(const a of configs){
  const fired = fireRules(C.rules, a, TAX), ruleOf = id => fired.has(id);
  const open = new Set(C.documents.filter(d=>docIncluded(d,a,TAX,ruleOf)).map(d=>d.id));
  denominator++;
  for(const c of drafting){
    if(!open.has(c.doc)) continue;
    if(clauseEligible(c,a,TAX,ruleOf)) reach.set(c.id, reach.get(c.id)+1);
  }
}
const pct = id => (100*reach.get(id)/denominator);

/* ---- ordering inside a document: cost of getting it wrong ---- */
const SEV = {critical:3, recommended:2, optional:1};
const weight = c => SEV[c.severity]*10 + (c.insertion==='auto'?6:0) + Math.round(pct(c.id)/10);

/* ---- which fields does this clause interpolate, and what are they ---- */
const fieldById = new Map(C.fields.map(f=>[f.id,f]));
function fieldsUsed(body){
  const ids = [...new Set([...String(body).matchAll(/\{\{([a-zA-Z0-9_.]+)\}\}/g)].map(m=>m[1]))];
  return ids.map(id=>({id, label: fieldById.get(id)?.label || fieldById.get(id)?.description || null}));
}
function xrefsUsed(body){
  return [...new Set([...String(body).matchAll(/<<xr:(@?\w+)>>/g)].map(m=>m[1]))];
}
function glossaryUsed(body){
  return [...new Set([...String(body).matchAll(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g)].map(m=>(m[2]||m[1]).toLowerCase()))];
}

/* ---- when does it appear, in words a reviewer can act on ---- */
function whenApplies(c){
  const bits = [];
  if(!c.jurisdictions.includes('*')) bits.push(`only in ${c.jurisdictions.join(', ')}`);
  if(!c.entities.includes('*'))      bits.push(`only for ${c.entities.join(', ')}`);
  if(!c.industries.includes('*'))    bits.push(`only for ${c.industries.join(', ')}`);
  if(c.condition)                    bits.push('conditional — see the condition block');
  return bits.length ? bits.join('; ') : 'every document of this type';
}

const byDoc = new Map();
for(const c of drafting.sort((a,b)=>weight(b)-weight(a))){
  if(!byDoc.has(c.doc)) byDoc.set(c.doc, []);
  byDoc.get(c.doc).push(c);
}
const docOrder = [...byDoc.keys()].sort((a,b)=>
  byDoc.get(b).reduce((s,c)=>s+weight(c),0) - byDoc.get(a).reduce((s,c)=>s+weight(c),0));

/* ---- the packet ---- */
const L = TAX.draftingReviewLevels;
const gate = TAX.releaseGate.draftingMinimum;

let md = `# Drafting review packet

${drafting.length} clauses across ${byDoc.size} documents${only?` (filtered to \`${only}\`)`:''}. None of them
asserts what the law requires, so none can be verified against a statute — they are graded
on drafting review instead, and the release gate for that ladder is **${gate}**.

Generated by \`templates/tools/drafting-packet.mjs\` from \`templates/\`. Do not edit this file;
record verdicts in the clause JSON, where the validator and the engine can see them.

## What is being asked

Three questions per clause, in order. The first two are what \`counsel-reviewed\` certifies;
the third is what \`counsel-approved\` adds.

1. **Does it do what it says?** Read it as drafted, with the field placeholders filled in.
   Does the sentence produce the obligation the title claims?
2. **Is it enforceable as written?** Ambiguity, a missing standard, an obligation with no
   bound, a term that a court would not give effect to.
3. **Is it the term we want?** For the posture this product takes — a small company, the
   package this document belongs to. This is a commercial judgement, not a legal one.

A clause that fails 1 or 2 is a defect. A clause that fails only 3 is a preference, and
should be recorded as such — the distinction is what keeps the review honest.

## How to record a verdict

Add a \`draftingReview\` block to the clause in \`templates/clauses/<file>.json\`:

\`\`\`json
"draftingReview": {
  "level": "${gate}",
  "reviewer": "Full Name",
  "role": "e.g. General Counsel, outside commercial counsel",
  "date": "YYYY-MM-DD",
  "scope": "what you read it against — the posture, the package, the counterparty type",
  "notes": "anything the next reader needs"
}
\`\`\`

The validator refuses a signoff that names no person, carries no date, states no scope, or
uses a reviewer name that is a team, a tool, or a model. \`self-reviewed\` sits below the
gate on purpose: an author checking their own work is not review. There is no level that
can be reached without a human, and adding citations to a drafting clause does nothing —
the two ladders are blind to each other.

## The ladder

| Level | Rank | Meaning |
|---|---|---|
${Object.entries(L).filter(([k])=>!k.startsWith('$'))
  .map(([k,v])=>`| \`${k}\`${k===gate?' **(gate)**':''} | ${v.rank} | ${v.meaning} |`).join('\n')}

`;

for(const doc of docOrder){
  const d = docById.get(doc);
  const cs = byDoc.get(doc);
  md += `\n---\n\n# ${d?.label || doc}\n\n`;
  md += `\`${doc}\` · ${cs.length} clause(s) for review · package \`${d?.package ?? '—'}\`\n\n`;
  md += `| # | Clause | Severity | Inserted | Appears in |\n|---|---|---|---|---|\n`;
  cs.forEach((c,i)=>{
    md += `| ${i+1} | [${c.title}](#${c.id}) | ${c.severity} | ${c.insertion} | ${pct(c.id).toFixed(0)}% |\n`;
  });
  md += '\n';

  cs.forEach((c,i)=>{
    const f = fieldsUsed(c.body), x = xrefsUsed(c.body), gl = glossaryUsed(c.body), talk = lawTalk(c);
    md += `\n### ${i+1}. ${c.title}\n\n`;
    md += `<a id="${c.id}"></a>\`${c.id}\` · ${c.group} · **${c.severity}** · ${c.insertion==='auto'?'drafted automatically':'offered as a suggestion'} · appears in **${pct(c.id).toFixed(0)}%** of generated documents\n\n`;
    md += `**Applies:** ${whenApplies(c)}\n\n`;
    if(c.rationale) md += `**Why it is here:** ${c.rationale}\n\n`;
    md += '**As drafted:**\n\n```\n' + String(c.body).trim() + '\n```\n\n';
    if(f.length) md += `**Fields interpolated:** ${f.map(v=>`\`{{${v.id}}}\`${v.label?` — ${v.label}`:''}`).join('; ')}\n\n`;
    if(x.length) md += `**Cross-references:** ${x.map(v=>`\`${v}\``).join(', ')} — the reference resolves to a clause, so check it still reads correctly if either side is reworded.\n\n`;
    if(gl.length) md += `**Plain-English terms shown to the user:** ${gl.map(v=>`${v} — "${(C.glossary[v]||'').replace(/"/g,'\'')}"`).join('; ')}\n\n`;
    if(talk.length) md += `> ⚠ This clause is classified as drafting but its body ${talk.join(', ')}. If it does assert law, it belongs on the authority track and this review cannot clear it.\n\n`;
    md += `**Verdict:** ☐ does what it says ☐ enforceable as written ☐ the term we want — ☐ defect ☐ preference\n\n`;
  });
}

const outDir = path.join(ROOT,'..','verification');
fs.mkdirSync(outDir,{recursive:true});
writeIfChanged(path.join(outDir,'drafting-review.md'), md, {linePatterns:VOLATILE_LINES, fsImpl:fs});

/* CSV for tracking, one row per clause */
const esc = v => `"${String(v??'').replace(/"/g,'""')}"`;
const csv = ['clause,document,group,title,severity,insertion,reach_pct,applies,law_talk,level,reviewer,role,date,scope']
  .concat(docOrder.flatMap(doc => byDoc.get(doc).map(c => [
    c.id, doc, c.group, c.title, c.severity, c.insertion, pct(c.id).toFixed(1),
    whenApplies(c), lawTalk(c).join('; '),
    c.draftingReview?.level || 'unreviewed', c.draftingReview?.reviewer || '',
    c.draftingReview?.role || '', c.draftingReview?.date || '', c.draftingReview?.scope || ''
  ].map(esc).join(','))))
  .join('\n');
writeIfChanged(path.join(outDir,'drafting-review.csv'), csv+'\n', {linePatterns:VOLATILE_LINES, fsImpl:fs});

/* ---- what the run found ---- */
const passing = drafting.filter(c=>gateFor(c,TAX).ok).length;
const withTalk = drafting.filter(c=>lawTalk(c).length);
console.log(`${drafting.length} drafting clause(s) across ${byDoc.size} document(s), measured over ${denominator} configurations`);
console.log(`  ${passing} at or above the "${gate}" gate, ${drafting.length-passing} awaiting review`);
const levels = drafting.reduce((m,c)=>{const l=c.draftingReview?.level||'unreviewed'; m[l]=(m[l]||0)+1; return m;},{});
console.log(`  by level: ${JSON.stringify(levels)}`);
if(withTalk.length) console.log(`  ${withTalk.length} clause(s) talk like a statute and may be misclassified: ${withTalk.map(c=>c.id).join(', ')}`);
const reachTop = [...drafting].sort((a,b)=>pct(b.id)-pct(a.id)).slice(0,5);
console.log(`  widest reach: ${reachTop.map(c=>`${c.id} ${pct(c.id).toFixed(0)}%`).join(', ')}`);
console.log(`written to verification/drafting-review.md and .csv`);
